"""create table

Revision ID: 6d49d6b1603c
Revises: 
Create Date: 2026-07-27 15:29:25.187169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d49d6b1603c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('number_room', sa.Integer(), nullable=False),
    sa.Column('office', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('room_id'),
    sa.UniqueConstraint('office', 'number_room', name='uq_rooms_office_number')
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('employee', 'admin', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('slot',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.CheckConstraint('start_time < end_time', name='ck_slot_time'),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('slot_id'),
    sa.UniqueConstraint('room_id', 'start_time', 'end_time', name='uq_slot_for_room')
    )
    op.create_table('booking',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.slot_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('booking_id'),
    sa.UniqueConstraint('booking_date', 'slot_id', name='uq_booking_date_slot')
    )
    op.create_index(op.f('ix_booking_staff_id'), 'booking', ['staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_staff_id'), table_name='booking')
    op.drop_table('booking')
    op.drop_table('slot')
    op.drop_table('staff')
    sa.Enum('employee', 'admin', name='role').drop(op.get_bind())
    op.drop_table('room')
    # ### end Alembic commands ###
