"""name staff username constraint

Revision ID: b635261c81ba
Revises: 6d49d6b1603c
Create Date: 2026-08-08 13:27:02.840111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b635261c81ba'
down_revision: Union[str, Sequence[str], None] = '6d49d6b1603c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('staff_username_key'), 'staff', type_='unique')
    op.create_unique_constraint('uq_staff_username', 'staff', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_staff_username', 'staff', type_='unique')
    op.create_unique_constraint(op.f('staff_username_key'), 'staff', ['username'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
